import java.sql.*;
import database.DBConnection;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gota
 */
public class billing extends javax.swing.JFrame {
    Connection connection;

    /**
     * Creates new form billing
     */
    public billing() {
        initComponents();
        connection = DBConnection.getDBConnection().getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSearchBContact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSearchBName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtSearchaPName = new javax.swing.JTextField();
        txtSearchPID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblRate = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 550));
        setMinimumSize(new java.awt.Dimension(1200, 550));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/billing frame.png"))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Billing ani.gif"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Time");

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDate.setText("09-04-2022");

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTime.setText("17:45:00");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Buyer Details");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Product Details");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Contact No ");

        txtSearchBContact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSearchBContact.setForeground(java.awt.Color.gray);
        txtSearchBContact.setText("Contact No");
        txtSearchBContact.setPreferredSize(new java.awt.Dimension(250, 22));
        txtSearchBContact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchBContactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchBContactFocusLost(evt);
            }
        });
        txtSearchBContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchBContactActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Name");
        jLabel8.setPreferredSize(new java.awt.Dimension(66, 16));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Email");
        jLabel9.setPreferredSize(new java.awt.Dimension(66, 16));

        txtSearchBName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSearchBName.setForeground(java.awt.Color.gray);
        txtSearchBName.setText("Buyer Name");
        txtSearchBName.setToolTipText("");
        txtSearchBName.setPreferredSize(new java.awt.Dimension(250, 22));
        txtSearchBName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchBNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchBNameFocusLost(evt);
            }
        });
        txtSearchBName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchBNameActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtSearchaPName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSearchaPName.setForeground(java.awt.Color.gray);
        txtSearchaPName.setText("Product Name");
        txtSearchaPName.setMaximumSize(new java.awt.Dimension(96, 22));
        txtSearchaPName.setMinimumSize(new java.awt.Dimension(96, 22));
        txtSearchaPName.setName(""); // NOI18N
        txtSearchaPName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchaPNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchaPNameFocusLost(evt);
            }
        });
        txtSearchaPName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchaPNameActionPerformed(evt);
            }
        });

        txtSearchPID.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtSearchPID.setForeground(java.awt.Color.gray);
        txtSearchPID.setText("ID");
        txtSearchPID.setMinimumSize(new java.awt.Dimension(44, 22));
        txtSearchPID.setPreferredSize(new java.awt.Dimension(44, 22));
        txtSearchPID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchPIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchPIDFocusLost(evt);
            }
        });
        txtSearchPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchPIDActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Product ID");
        jLabel10.setPreferredSize(new java.awt.Dimension(66, 16));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Name");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Rate");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Description");

        lblRate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblDescription.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchBName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearchBContact, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchPID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchaPName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblDate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblTime))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchBName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearchBContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchPID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtSearchaPName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(lblRate)
                    .addComponent(lblDescription))
                .addGap(353, 353, 353))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchBContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchBContactActionPerformed
        searchBuyer();
    }//GEN-LAST:event_txtSearchBContactActionPerformed

    private void txtSearchaPNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchaPNameFocusGained
        txtSearchaPName.setText("");
        txtSearchaPName.setForeground(Color.BLACK);
        
        txtSearchPID.setText("ID");
        txtSearchPID.setForeground(Color.GRAY);
    }//GEN-LAST:event_txtSearchaPNameFocusGained

    private void txtSearchaPNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchaPNameFocusLost
        if(txtSearchaPName.getText().equals("")){
            txtSearchaPName.setText("Product Name");
            txtSearchaPName.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtSearchaPNameFocusLost

    private void txtSearchaPNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchaPNameActionPerformed
        searchProduct();
    }//GEN-LAST:event_txtSearchaPNameActionPerformed

    private void txtSearchPIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchPIDFocusGained
        txtSearchPID.setText("");
        txtSearchPID.setForeground(Color.BLACK);
            
        txtSearchaPName.setText("Product Name");
        txtSearchaPName.setForeground(Color.GRAY);
    }//GEN-LAST:event_txtSearchPIDFocusGained

    private void txtSearchPIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchPIDFocusLost
        if(txtSearchPID.getText().equals("")){
            txtSearchPID.setText("ID");
            txtSearchPID.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtSearchPIDFocusLost

    private void txtSearchPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchPIDActionPerformed
        searchProduct();
    }//GEN-LAST:event_txtSearchPIDActionPerformed

    private void txtSearchBNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchBNameActionPerformed
        searchBuyer();
    }//GEN-LAST:event_txtSearchBNameActionPerformed

    private void txtSearchBNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchBNameFocusGained
        txtSearchBName.setText("");
        txtSearchBName.setForeground(Color.BLACK);
        
        txtSearchBContact.setText("Contact No");
        txtSearchBContact.setForeground(Color.GRAY);
    }//GEN-LAST:event_txtSearchBNameFocusGained

    private void txtSearchBNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchBNameFocusLost
       if(txtSearchBName.getText().equals("")){
            txtSearchBName.setText("Buyer Name");
            txtSearchBName.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtSearchBNameFocusLost

    private void txtSearchBContactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchBContactFocusGained
        txtSearchBContact.setText("");
        txtSearchBContact.setForeground(Color.BLACK);
        
        txtSearchBName.setText("Buyer Name");
        txtSearchBName.setForeground(Color.GRAY);
    }//GEN-LAST:event_txtSearchBContactFocusGained

    private void txtSearchBContactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchBContactFocusLost
        if(txtSearchBContact.getText().equals("")){
            txtSearchBContact.setText("Contact No");
            txtSearchBContact.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtSearchBContactFocusLost

    private void searchBuyer(){
        String query;
        if(txtSearchBContact.getText().equals("Contact No"))
            query = "select * from buyer where name = '"+ txtSearchBName.getText() +"'";
        else
            query = "select * from buyer where contact_no = '"+ txtSearchBContact.getText() +"'";
        
        try {
            Statement statement = connection.createStatement();
            ResultSet result = statement.executeQuery(query);
            if(result.next() ){
                txtSearchBName.setText(result.getString(2));
                txtSearchBName.setForeground(Color.BLACK);
                txtSearchBContact.setText(result.getString(4));
                txtSearchBContact.setForeground(Color.BLACK);
                lblEmail.setText(result.getString(5));
            }else{
                setAlwaysOnTop(false);
                JOptionPane.showMessageDialog(null, "Buyer does not exist","",1);
                setAlwaysOnTop(true);
                if(txtSearchBContact.getText().equals("Contact No"))
                    txtSearchBName.requestFocus();
                else
                    txtSearchBContact.requestFocus();
            }
        } catch (SQLException ex) {
        }
    }
    
    private void searchProduct(){
        String query;
        if(txtSearchPID.getText().equals("ID"))
            query = "select * from product where product_name = '"+ txtSearchaPName.getText() +"'";
        else
            query = "select * from product where product_id = '"+ txtSearchPID.getText() +"'";

        try {
            Statement statement = connection.createStatement();
            ResultSet result = statement.executeQuery(query);
            if(result.next() ){
                if(result.getString(5).equals("Yes")){
                    txtSearchPID.setText(result.getString(1));
                    txtSearchPID.setForeground(Color.BLACK);
                    txtSearchaPName.setText(result.getString(2));
                    txtSearchaPName.setForeground(Color.BLACK);
                    lblRate.setText(result.getString(3));
                    lblDescription.setText(result.getString(4));
                }else{
                    setAlwaysOnTop(false);
                    JOptionPane.showMessageDialog(null, "Product is not active","",1);
                    setAlwaysOnTop(true);
                    if(txtSearchPID.getText().equals("ID"))
                        txtSearchaPName.requestFocus();
                    else
                        txtSearchPID.requestFocus();
                }
            }else{
                setAlwaysOnTop(false);
                JOptionPane.showMessageDialog(null, "Product does not exist","",1);
                setAlwaysOnTop(true);
                if(txtSearchPID.getText().equals("ID"))
                    txtSearchaPName.requestFocus();
                else
                    txtSearchPID.requestFocus();
            }
        } catch (SQLException ex) {
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblRate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtSearchBContact;
    private javax.swing.JTextField txtSearchBName;
    private javax.swing.JTextField txtSearchPID;
    private javax.swing.JTextField txtSearchaPName;
    // End of variables declaration//GEN-END:variables
}
